services:
  sterility-ai:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: sterility-ai
    image: sterility-ai:latest
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models:ro
      - ./src/app.py:/app/app.py
    environment:
      - MODEL_PATH=/app/models/efficientnet_b0_tune_sterility_v0.0.1.pth
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_SERVER_FILE_WATCHER_TYPE=auto
      - STREAMLIT_SERVER_RUN_ON_SAVE=true
      - PYTHONUNBUFFERED=1
      - CUDA_VISIBLE_DEVICES=""
    command: [
      "streamlit", "run", "./app.py",
      "--server.address", "0.0.0.0",
      "--server.port", "8501",
      "--server.fileWatcherType", "auto",
      "--server.runOnSave", "true"
    ]
